### ISSUE TITLE
Stencil support

### ISSUE THREAD

**Issue by ehsantn** [IntelLabs/numba#17]
Let's get started on stencils (required for urgent HPAT features). I created a branch called `stencil` for a quick first iteration. Here is an example code for start:

```python
@numba.njit(parallel=True)
def f(A, B):
    numba.stencil(A, B, lambda a: 0.25 * (a[0,1] + a[1,0] + a[0,-1] + a[-1,0]))
    return B
```
@ninegua @DrTodd13

**Comment by ninegua** [comment]
For reference, [the API we had in ParallelAccelerator for Julia](https://github.com/IntelLabs/ParallelAccelerator.jl/blob/master/doc/advanced.rst#stencil) would translate to the following python API:

~~~ python
stencil(kernel_function, buffer1, buffer2, ..., iteration = NUMBER, boundary = STRING)
~~~

An example would be:

~~~ python
@numba.njit(parallel=True)
def f(A, B):
    def kernel(b, a):
        b[0,0] = 0.25 * (a[0,1] + a[1,0] + a[0,-1] + a[-1,0])
        return a, b
    numba.stencil(kernel, B, A, iteration=1, boundary='oob_skip')
    return B
~~~

There are several advantages to this design:

1. kernel function is given in the first argument, so that the list of buffers can be varargs, and we can leave iteration count and boundary handling to be keyword arguments. This also helps if we want to have a reference implementation of the same API as a pure Python function (i.e., without Numba compiler).

2. The list of buffers would match the formal parameter list of the kernel function, in which all buffers are relatively indexed with positive or negative integer constants. 

3. There can be multiple inputs and outputs too, and the list of buffers given as arguments to `stencil` call do not differentiate between input/output. They are only differentiated in the kernel function: outputs are on the left-hand-side of an assignment, and only accessed by 0-index, and outputs can also be inputs (which can actually happen, as in the case of [3DFD stencil](https://sfederation.intel.com/affwebservices/public/saml2sso?SPID=idz-prod&ProtocolBinding=urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST&RelayState=https%3A%2F%2Fsoftware%2Eintel%2Ecom%2Fen-us%2Farticles%2Feight-optimizations-for-3-dimensional-finite-difference-3dfd-code-with-an-isotropic-iso)). So it is very flexible.

4. In case of iterative stencil (where iteration argument is given), the kernel function must have a return statement that returns a list of buffers that serves as a specification of buffer rotation. In the example above, the kernel function takes in `(a, b)` and returns `(b, a)`, which means the input and output are swapped. It is also entirely possible to keep some buffers at a fixed position so that they do not rotate (while enjoying the same convenience of relative indice as other buffers).

5. The `boundary` argument can be one of the following strings (please note that writing to output buffers is never out-of-bound due to the 0-index requirement, so only indexing input buffers can be out-of-bounds):

    * `'oob_skip'`: Writing to output is skipped when input indexing is out-of-bound.
    * `'oob_wraparound'`: Indexing is "wrapped around" at the array boundaries so they are always safe.
    * `'oob_dst_zero'`: Write 0 to the output array when any of the input indices is out-of-bounds.
    * `'oob_src_zero'`: Assume 0 is returned by a read operation when indexing is out-of-bounds.

6. Having both `iteration` and `boundary` as keyword argument to `stencil` call is an enabler to more advanced optimizations (e.g., [combining time-skewing and spatial-blocking](http://people.csail.mit.edu/skamil/projects/stencilprobe/)) that is hard to do with a plain loop over single-step stencils. We can also have default values `iteration=1` and `boundary='skip'` when they are not given.

Possible drawbacks to this API design are:

1. Some iterative stencil terminates based on a conditional rather than an iteration count, which is hard to express here. The fallback would be to have a while-loop over single step stencil call.

2. Python's lambda forbids assignments or multi-line statements, so the kernel has to be defined separately as an inner function. 

Consider the flexibility this API allows, I'd still recommend taking this approach, or consider simple lambdas (where a single scalar value is returned instead of a buffer list) as a degenerated case.
