### ISSUE TITLE
Blackscholes error in parallel backend

### ISSUE THREAD

**Issue by ehsantn** [IntelLabs/numba#7]
With Python 3.5:
PYTHONHASHSEED=2 python blackscholes_pa.py
throws an error during parfor lowering in the parallel gufunc backend. sequential lowering works.

**Comment by ninegua** [comment]
The problem looks like different behavior of fusion that leaves `cndf2` inside the loop body but its definition outside the loop. So if the loop body contains:

```
    $0.30 = global(cndf2: <numba._DUFunc 'cndf2'>) ['$0.30']
    $expr_out_var.68 = call $0.30($arg_out_var.69, args=[Var($arg_out_var.69, blackscholes_pa.py (21))], func=$0.30, kws=(), vararg=None) ['$0.30', '$arg_out_var.69', '$expr_out_var.68']
```

Then there won't be any issue. But if the assignment of `$0.30` gets pulled outside the parfor loop, then the produced kernel function will have it as one of the parameters, and eventually raises `NotImplementedError("cannot convert %s to native value" % (typ,))` error.

The problem is spotted by comparing different outputs between:
```
NUMBA_DUMP_IR=1 NUMBA_DEBUG_ARRAY_OPT=1 NUMBA_DIFF_IR=1 python3 blackscholes_pa.py
```
and
``` 
PYTHONHASHSEED=2 NUMBA_DUMP_IR=1 NUMBA_DEBUG_ARRAY_OPT=1 NUMBA_DIFF_IR=1 python3 blackscholes_pa.py
```

Also with `PYTHONHASHSEED=2` not all loops are fused, so it ends up with several kernels.

**Comment by ninegua** [comment]
BTW, I can only reproduce this problem in one of my setups (on psephi03). I cannot reproduce it in my other two setups (one with python 3.5.2, the other one with python 3.6.1), either with or without setting `PYTHONHASHSEED`.

**Comment by ninegua** [comment]
Fixed.
